replicaCount: 1

image:
  repository: ghcr.io/briangtn/blue-prince-note-helper
  tag: mas
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: blueprince.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi

auth:
  roUser: ""
  roPass: ""
  rwUser: ""
  rwPass: ""

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
