replicaCount: 1

image:
  repository: blueprince-helper
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: blueprince.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
