apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blueprince-helper.fullname" . }}-auth
  labels:
    {{- include "blueprince-helper.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: "Prune=false"
type: Opaque
data:
  AUTH_RO_PASS: {{ .Values.auth.roPass | default "" | b64enc | quote }}
  AUTH_RW_PASS: {{ .Values.auth.rwPass | default "" | b64enc | quote }}
