// Catalogue de pièces Blue Prince (connaissances du jeu).
// Quand tu tapes EXACTEMENT le nom d'une pièce, l'app remplit auto type + coût gemmes.
// type = catégorie (couleur de drafting) ; gem = coût en gemmes pour drafter (null = inconnu/gratuit).
// ⚠️ Coûts au mieux de mes connaissances — à corriger en jeu si besoin.
//
// Catégories utilisées (= types prédéfinis de l'app, couleur de bordure du jeu) :
//   Blueprints, Bedrooms, Hallways, Green rooms, Shops, Red rooms, Secret rooms
// Source : https://blue-prince.fandom.com/wiki/Room_Directory
const RAW = {
  // --- Hallways ---
  'Hallway': ['Hallways', 0],
  'West Wing Hall': ['Hallways', 0],
  'East Wing Hall': ['Hallways', 0],
  'Corridor': ['Hallways', 0],
  'Passageway': ['Hallways', 0],
  'Secret Passage': ['Hallways', 0],
  'Foyer': ['Hallways', 0],
  'Great Hall': ['Hallways', 0],
  'Entrance Hall': ['Hallways', 0],
  'Spiral Staircase': ['Hallways', 0],

  // --- Bedrooms ---
  'Bedroom': ['Bedrooms', 0],
  'Boudoir': ['Bedrooms', 0],
  'Guest Bedroom': ['Bedrooms', 0],
  'Nursery': ['Bedrooms', 0],
  "Servant's Quarters": ['Bedrooms', 0],
  'Bunk Room': ['Bedrooms', 0],
  "Her Ladyship's Chamber": ['Bedrooms', 0],
  'Master Bedroom': ['Bedrooms', 0],

  // --- Green rooms (extérieur / jardin) ---
  'Terrace': ['Green rooms', null],
  'Patio': ['Green rooms', null],
  'Courtyard': ['Green rooms', null],
  'Cloister': ['Green rooms', null],
  'Veranda': ['Green rooms', null],
  'Greenhouse': ['Green rooms', null],
  'Morning Room': ['Green rooms', null],
  'Secret Garden': ['Green rooms', null],

  // --- Shops (coûtent des gemmes) ---
  'Commissary': ['Shops', null],
  'Kitchen': ['Shops', null],
  'Locksmith': ['Shops', null],
  'Showroom': ['Shops', null],
  'Laundry Room': ['Shops', null],
  'Bookshop': ['Shops', null],
  'The Armory': ['Shops', null],
  'Gift Shop': ['Shops', null],

  // --- Red rooms (pièces néfastes) ---
  'Lavatory': ['Red rooms', null],
  'Chapel': ['Red rooms', null],
  "Maid's Chamber": ['Red rooms', null],
  'Archives': ['Red rooms', null],
  'Gymnasium': ['Red rooms', null],
  'Darkroom': ['Red rooms', null],
  'Weight Room': ['Red rooms', null],
  'Furnace': ['Red rooms', null],

  // --- Secret rooms (bordure noire : Studio Additions, Found Floorplans, Outer Rooms) ---
  'Dovecote': ['Secret rooms', null],
  'The Kennel': ['Secret rooms', null],
  'Clock Tower': ['Secret rooms', null],
  'Classroom': ['Secret rooms', null],
  'Solarium': ['Secret rooms', null],
  'Dormitory': ['Secret rooms', null],
  'Vestibule': ['Secret rooms', null],
  'Casino': ['Secret rooms', null],
  'Planetarium': ['Secret rooms', null],
  'Mechanarium': ['Secret rooms', null],
  'Treasure Trove': ['Secret rooms', null],
  'Throne Room': ['Secret rooms', null],
  'Tunnel': ['Secret rooms', null],
  'Conservatory': ['Secret rooms', null],
  'Lost & Found': ['Secret rooms', null],
  'Closed Exhibit': ['Secret rooms', null],
  'Throne of the Blue Prince': ['Secret rooms', null],
  'Toolshed': ['Secret rooms', null],
  'Shelter': ['Secret rooms', null],
  'Schoolhouse': ['Secret rooms', null],
  'Shrine': ['Secret rooms', null],
  'Root Cellar': ['Secret rooms', null],
  'Hovel': ['Secret rooms', null],
  'Trading Post': ['Secret rooms', null],
  'Tomb': ['Secret rooms', null],

  // --- Blueprints (salles standard, bordure bleue) ---
  'The Foundation': ['Blueprints', null],
  'Spare Room': ['Blueprints', null],
  'Rotunda': ['Blueprints', null],
  'Parlor': ['Blueprints', null],
  'Billiard Room': ['Blueprints', null],
  'Gallery': ['Blueprints', null],
  'Room 8': ['Blueprints', null],
  'Closet': ['Blueprints', null],
  'Walk-in Closet': ['Blueprints', null],
  'Attic': ['Blueprints', null],
  'Storeroom': ['Blueprints', null],
  'Nook': ['Blueprints', null],
  'Garage': ['Blueprints', null],
  'Music Room': ['Blueprints', null],
  'Locker Room': ['Blueprints', null],
  'Den': ['Blueprints', null],
  'Wine Cellar': ['Blueprints', null],
  'Trophy Room': ['Blueprints', null],
  'Ballroom': ['Blueprints', null],
  'Pantry': ['Blueprints', null],
  'Rumpus Room': ['Blueprints', null],
  'Vault': ['Blueprints', null],
  'Office': ['Blueprints', null],
  'Drawing Room': ['Blueprints', null],
  'Study': ['Blueprints', null],
  'Library': ['Blueprints', null],
  'Chamber of Mirrors': ['Blueprints', null],
  'The Pool': ['Blueprints', null],
  'Drafting Studio': ['Blueprints', null],
  'Utility Closet': ['Blueprints', null],
  'Boiler Room': ['Blueprints', null],
  'Pump Room': ['Blueprints', null],
  'Security': ['Blueprints', null],
  'Workshop': ['Blueprints', null],
  'Laboratory': ['Blueprints', null],
  'Sauna': ['Blueprints', null],
  'Coat Check': ['Blueprints', null],
  'Mail Room': ['Blueprints', null],
  'Freezer': ['Blueprints', null],
  'Dining Room': ['Blueprints', null],
  'Observatory': ['Blueprints', null],
  'Conference Room': ['Blueprints', null],
  'Aquarium': ['Blueprints', null],
  'Antechamber': ['Blueprints', null],
  'Room 46': ['Blueprints', null],
}

// index insensible à la casse / espaces
const INDEX = {}
for (const [name, [type, gem]] of Object.entries(RAW)) {
  INDEX[name.toLowerCase().trim()] = { name, type, gem }
}

export function lookupRoom(name) {
  if (!name) return null
  return INDEX[name.toLowerCase().trim()] || null
}

export const KNOWN_ROOM_NAMES = Object.keys(RAW)

const CDN = 'https://static.wikia.nocookie.net/blue-prince/images'

// URLs CDN directes (évite le redirect Fandom qui bloque dans le navigateur)
const ICON_URLS = {
  'Antechamber':         `${CDN}/6/63/Antechamber_Icon.png/revision/latest`,
  'Entrance Hall':       `${CDN}/6/67/Entrance_Hall_Icon.png/revision/latest`,
  'Corridor':            `${CDN}/0/09/Corridor_Icon.png/revision/latest`,
  'Hallway':             `${CDN}/8/82/Hallway_Icon.png/revision/latest`,
  'Passageway':          `${CDN}/1/14/Passageway_Icon.png/revision/latest`,
  'West Wing Hall':      `${CDN}/8/8c/West_Wing_Hall_Icon.png/revision/latest`,
  'East Wing Hall':      `${CDN}/1/18/East_Wing_Hall_Icon.png/revision/latest`,
  'Great Hall':          `${CDN}/6/6d/Great_Hall_Icon.png/revision/latest`,
  'Foyer':               `${CDN}/8/8e/Foyer_Icon.png/revision/latest`,
  'Secret Passage':      `${CDN}/8/81/Secret_Passage_Icon.png/revision/latest`,
  'Bedroom':             `${CDN}/f/f3/Bedroom_Icon.png/revision/latest`,
  'Master Bedroom':      `${CDN}/3/39/Master_Bedroom_Icon.png/revision/latest`,
  'Guest Bedroom':       `${CDN}/8/8d/Guest_Bedroom_Icon.png/revision/latest`,
  'Boudoir':             `${CDN}/3/38/Boudoir_Icon.png/revision/latest`,
  'Nursery':             `${CDN}/e/e5/Nursery_Icon.png/revision/latest`,
  'Bunk Room':           `${CDN}/a/a3/Bunk_Room_Icon.png/revision/latest`,
  'Spare Room':          `${CDN}/7/70/Spare_Room_Icon.png/revision/latest`,
  "Servant's Quarters":   `${CDN}/5/5b/Servant%27s_Quarters_Icon.png/revision/latest`,
  "Maid's Chamber":      `${CDN}/0/00/Maid%27s_Chamber_Icon.png/revision/latest`,
  "Her Ladyship's Chamber":`${CDN}/b/b3/Her_Ladyship%27s_Chamber_Icon.png/revision/latest`,
  'Greenhouse':          `${CDN}/0/0d/Greenhouse_Icon.png/revision/latest`,
  'Conservatory':        `${CDN}/9/97/Conservatory_Icon.png/revision/latest`,
  'Courtyard':           `${CDN}/3/3d/Courtyard_Icon.png/revision/latest`,
  'Veranda':             `${CDN}/2/25/Veranda_Icon.png/revision/latest`,
  'Patio':               `${CDN}/6/6c/Patio_Icon.png/revision/latest`,
  'Terrace':             `${CDN}/f/f4/Terrace_Icon.png/revision/latest`,
  'Secret Garden':       `${CDN}/0/09/Secret_Garden_Icon.png/revision/latest`,
  'Commissary':          `${CDN}/d/df/Commissary_Icon.png/revision/latest`,
  'Showroom':            `${CDN}/9/96/Showroom_Icon.png/revision/latest`,
  'Locksmith':           `${CDN}/5/55/Locksmith_Icon.png/revision/latest`,
  'Furnace':             `${CDN}/9/9b/Furnace_Icon.png/revision/latest`,
  'Tomb':                `${CDN}/a/a7/Tomb_Icon.png/revision/latest`,
  'Boiler Room':         `${CDN}/3/3e/Boiler_Room_Icon.png/revision/latest`,
  'Chapel':              `${CDN}/f/f4/Chapel_Icon.png/revision/latest`,
  'Cloister':            `${CDN}/a/a7/Cloister_Icon.png/revision/latest`,
  'Shrine':              `${CDN}/e/e3/Shrine_Icon.png/revision/latest`,
  'Morning Room':        `${CDN}/e/e1/Morning_Room_Icon.png/revision/latest`,
  'Aquarium':            `${CDN}/5/5a/Aquarium_Icon.png/revision/latest`,
  'Kitchen':             `${CDN}/7/75/Kitchen_Icon.png/revision/latest`,
  'Pantry':              `${CDN}/b/ba/Pantry_Icon.png/revision/latest`,
  'Dining Room':         `${CDN}/e/e1/Dining_Room_Icon.png/revision/latest`,
  'Drawing Room':        `${CDN}/c/c7/Drawing_Room_Icon.png/revision/latest`,
  'Parlor':              `${CDN}/1/1b/Parlor_Icon.png/revision/latest`,
  'Den':                 `${CDN}/8/85/Den_Icon.png/revision/latest`,
  'Study':               `${CDN}/8/8a/Study_Icon.png/revision/latest`,
  'Office':              `${CDN}/e/e4/Office_Icon.png/revision/latest`,
  'Library':             `${CDN}/4/41/Library_Icon.png/revision/latest`,
  'Billiard Room':       `${CDN}/f/fb/Billiard_Room_Icon.png/revision/latest`,
  'Nook':                `${CDN}/b/b6/Nook_Icon.png/revision/latest`,
  'Storeroom':           `${CDN}/2/29/Storeroom_Icon.png/revision/latest`,
  'Workshop':            `${CDN}/b/bc/Workshop_Icon.png/revision/latest`,
  'Laboratory':          `${CDN}/3/37/Laboratory_Icon.png/revision/latest`,
  'Walk-in Closet':      `${CDN}/4/41/Walk-in_Closet_Icon.png/revision/latest`,
  'Lavatory':            `${CDN}/4/46/Lavatory_Icon.png/revision/latest`,
  'Garage':              `${CDN}/1/1b/Garage_Icon.png/revision/latest`,
  'Hovel':               `${CDN}/9/91/Hovel_Icon.png/revision/latest`,
  'Archives':            `${CDN}/a/a2/Archives_Icon.png/revision/latest`,
  'Bookshop':            `${CDN}/d/db/Bookshop_Icon.png/revision/latest`,
  'Classroom':           `${CDN}/4/4a/Classroom_Icon.png/revision/latest`,
  'Clock Tower':         `${CDN}/f/fc/Clock_Tower_Icon.png/revision/latest`,
  'Dormitory':           `${CDN}/2/20/Dormitory_Icon.png/revision/latest`,
  'Gymnasium':           `${CDN}/a/a7/Gymnasium_Icon.png/revision/latest`,
  'Laundry Room':        `${CDN}/2/2a/Laundry_Room_Icon.png/revision/latest`,
  'Planetarium':         `${CDN}/f/f5/Planetarium_Icon.png/revision/latest`,
  'Solarium':            `${CDN}/f/fe/Solarium_Icon.png/revision/latest`,
  'The Armory':          `${CDN}/1/14/The_Armory_Icon.png/revision/latest`,
  'Vestibule':           `${CDN}/1/1b/Vestibule_Icon.png/revision/latest`,
  'Weight Room':         `${CDN}/7/72/Weight_Room_Icon.png/revision/latest`,
  'Casino':              `${CDN}/2/25/Casino_Icon.png/revision/latest`,
  'Darkroom':            `${CDN}/9/95/Darkroom_Icon.png/revision/latest`,
  'Dovecote':            `${CDN}/a/a1/Dovecote_Icon.png/revision/latest`,
  'Mechanarium':         `${CDN}/4/41/Mechanarium_Icon.png/revision/latest`,
  'The Kennel':          `${CDN}/d/d3/The_Kennel_Icon.png/revision/latest`,
  'Attic':               `${CDN}/2/2c/Attic_Icon.png/revision/latest`,
  'Closed Exhibit':      `${CDN}/f/f9/Closed_Exhibit_Icon.png/revision/latest`,
  'Closet':              `${CDN}/4/43/Closet_Icon.png/revision/latest`,
  'Locker Room':         `${CDN}/0/0d/Locker_Room_Icon.png/revision/latest`,
  'Music Room':          `${CDN}/f/fe/Music_Room_Icon.png/revision/latest`,
  'Rotunda':             `${CDN}/9/93/Rotunda_Icon.png/revision/latest`,
  'The Foundation':      `${CDN}/6/62/The_Foundation_Icon.png/revision/latest`,
  'Treasure Trove':      `${CDN}/8/87/Treasure_Trove_Icon.png/revision/latest`,
  'Gallery':             `${CDN}/0/0b/Gallery_Icon.png/revision/latest`,
  'Lost & Found':        `${CDN}/b/b2/Lost_%26_Found_Icon.png/revision/latest`,
  'Room 8':              `${CDN}/0/01/Room_8_Icon.png/revision/latest`,
  'Root Cellar':         `${CDN}/4/4d/Root_Cellar_Icon.png/revision/latest`,
  'Schoolhouse':         `${CDN}/f/f7/Schoolhouse_Icon.png/revision/latest`,
  'Shelter':             `${CDN}/2/2e/Shelter_Icon.png/revision/latest`,
  'Throne Room':         `${CDN}/9/90/Throne_Room_Icon.png/revision/latest`,
  'Toolshed':            `${CDN}/5/5e/Toolshed_Icon.png/revision/latest`,
  'Trading Post':        `${CDN}/7/76/Trading_Post_Icon.png/revision/latest`,
  'Tunnel':              `${CDN}/6/64/Tunnel_Icon.png/revision/latest`,
  'Wine Cellar':         `${CDN}/d/d7/Wine_Cellar_Icon.png/revision/latest`,
  'Throne of the Blue Prince': `${CDN}/4/42/Throne_Of_The_Blue_Prince_Icon.png/revision/latest`,
  'Ballroom':            `${CDN}/a/ac/Ballroom_Icon.png/revision/latest`,
  'Drafting Studio':     `${CDN}/5/58/Drafting_Studio_Icon.png/revision/latest`,
  'Freezer':             `${CDN}/3/33/Freezer_Icon.png/revision/latest`,
  'Observatory':         `${CDN}/e/ed/Observatory_Icon.png/revision/latest`,
  'Pump Room':           `${CDN}/3/37/Pump_Room_Icon.png/revision/latest`,
  'Room 46':             `${CDN}/d/d8/Room_46_Icon.png/revision/latest`,
  'Rumpus Room':         `${CDN}/9/94/Rumpus_Room_Icon.png/revision/latest`,
  'Sauna':               `${CDN}/c/c2/Sauna_Icon.png/revision/latest`,
  'Security':            `${CDN}/a/a9/Security_Icon.png/revision/latest`,
  'The Pool':            `${CDN}/1/1c/The_Pool_Icon.png/revision/latest`,
  'Vault':               `${CDN}/f/fe/Vault_Icon.png/revision/latest`,
  'Chamber of Mirrors':  `${CDN}/0/0c/Chamber_of_Mirrors_Icon.png/revision/latest`,
  'Coat Check':          `${CDN}/8/8f/Coat_Check_Icon.png/revision/latest`,
  'Conference Room':     `${CDN}/a/a2/Conference_Room_Icon.png/revision/latest`,
  'Mail Room':           `${CDN}/1/1c/Mail_Room_Icon.png/revision/latest`,
  'Trophy Room':         `${CDN}/0/05/Trophy_Room_Icon.png/revision/latest`,
  'Utility Closet':      `${CDN}/7/75/Utility_Closet_Icon.png/revision/latest`,
  // Pas d'icône sur le wiki : Spiral Staircase, Gift Shop
}

export function roomIconUrl(name) {
  if (!name) return null
  return ICON_URLS[name] ?? null
}
